{% set name = "osmnx" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 90ce2f82ecfe5b0db013b6fc35789efd09491a5493680005b02710ea0b6aaa9b

build:
  number: 0

outputs:
  - name: {{ name }}-base
    build:
      noarch: python
    script: build_base.sh
    requirements:
      host:
        - uv-build
        - pip
        - python {{ python_min }}
      run:
        # required dependencies' min versions from package's pyproject.toml
        - geopandas >=1.0
        - networkx >=2.5
        - numpy >=1.22
        - pandas >=1.4
        - python >={{ python_min }}
        - requests >=2.27
        - shapely >=2.0
    test:
      commands:
        - python -m pip check
      imports:
        - osmnx
      requires:
        - pip
        - python {{ python_min }}

  - name: {{ name }}
    build:
      noarch: python
    requirements:
      run:
        # optional dependencies' min versions from package's pyproject.toml
        - matplotlib-base >=3.5
        - rasterio >=1.3
        - rio-vrt >=0.3
        - scikit-learn >=1.0
        - scipy >=1.8
        - {{ pin_subpackage('osmnx-base', exact=True) }}
    test:
      commands:
        - python -m pip check
      imports:
        - osmnx
        - matplotlib
        - rasterio
        - rio_vrt
        - scipy
        - sklearn
      requires:
        - pip
        - python {{ python_min }}

about:
  home: https://osmnx.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: OSMnx is a Python package to easily download, model, analyze, and visualize street networks and other geospatial features from OpenStreetMap.
  description: OSMnx is a Python package to easily download, model, analyze, and visualize street networks and other geospatial features from OpenStreetMap. You can download and model walking, driving, or biking networks with a single line of code then analyze and visualize them. You can just as easily work with urban amenities/points
    of interest, building footprints, transit stops, elevation data, street orientations, speed/travel time, and routing.
  doc_url: https://osmnx.readthedocs.io
  dev_url: https://github.com/gboeing/osmnx

extra:
  recipe-maintainers:
    - gboeing
    - ocefpaf
