{% set name = "osmnx" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0175ab8710bb973cb7cc76c33eeddd670d9d2f4b444da08a1080c470844add2b

build:
  number: 0

outputs:
  - name: {{ name }}-base
    build:
      noarch: python
    script: build_base.sh
    requirements:
      host:
        - uv-build
        - pip
        - python >=3.11
      run:
        # required dependencies' min versions from package's pyproject.toml
        - geopandas >=1.0.1
        - networkx >=2.5
        - numpy >=1.24
        - pandas >=1.5
        - python >=3.11
        - requests >=2.30
        - shapely >=2.0
    test:
      commands:
        - python -m pip check
      imports:
        - osmnx
      requires:
        - pip
        - python >=3.11

  - name: {{ name }}
    build:
      noarch: python
    requirements:
      run:
        # optional dependencies' min versions from package's pyproject.toml
        - matplotlib-base >=3.6
        - rasterio >=1.4
        - rio-vrt >=0.3
        - scikit-learn >=1.2
        - scipy >=1.10
        - {{ pin_subpackage('osmnx-base', exact=True) }}
    test:
      commands:
        - python -m pip check
      imports:
        - osmnx
        - matplotlib
        - rasterio
        - rio_vrt
        - scipy
        - sklearn
      requires:
        - pip
        - python >=3.11

about:
  home: https://osmnx.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: OSMnx is a Python package to easily download, model, analyze, and visualize street networks and other geospatial features from OpenStreetMap.
  description: OSMnx is a Python package to easily download, model, analyze, and visualize street networks and other geospatial features from OpenStreetMap. You can download and model walking, driving, or biking networks with a single line of code then analyze and visualize them. You can just as easily work with urban 
    amenities/points of interest, building footprints, transit stops, elevation data, street orientations, speed/travel time, and routing.
  doc_url: https://osmnx.readthedocs.io
  dev_url: https://github.com/gboeing/osmnx

extra:
  recipe-maintainers:
    - gboeing
    - ocefpaf
