{% set name = "osmnx" %}
{% set version = "1.9.3" %}
{% set sha256 = "22548d86d68d36edff3cf9ab76c45745cda86a4ea0b28442e107d6b42992a426" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch
    - pip
    - python >=3.8
  run:
    - folium
    - gdal
    - geopandas
    - matplotlib-base
    - networkx
    - numpy
    - pandas
    - python >=3.8
    - rasterio
    - requests
    - scipy
    - scikit-learn
    - shapely >=2.0

test:
  imports:
    - osmnx

about:
  home: https://osmnx.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: OSMnx is a Python package to easily download, model, analyze, and visualize street networks and other geospatial features from OpenStreetMap.
  description: OSMnx is a Python package to easily download, model, analyze, and visualize street networks and other geospatial features from OpenStreetMap. You can download and model walking, driving, or biking networks with a single line of code then analyze and visualize them. You can just as easily work with urban amenities/points of interest, building footprints, transit stops, elevation data, street orientations, speed/travel time, and routing.
  doc_url: https://osmnx.readthedocs.io
  dev_url: https://github.com/gboeing/osmnx

extra:
  recipe-maintainers:
    - gboeing
    - ocefpaf
