{% set name = "osmnx" %}
{% set base = "osmnx-base" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4fd2eb3736cea503be94ab18d31a669addbaf2dd6a8249527cef94163bb93975

build:
  number: 4

outputs:
  - name: {{ base }}
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - hatchling
        - pip
      run:
        - python >={{ python_min }}
        - geopandas >=1.0
        - networkx >=2.5
        - numpy >=1.22
        - pandas >=1.4
        - requests >=2.27
        - shapely >=2.0

    test:
      commands:
        - python -m pip check
      imports:
        - osmnx
      requires:
        - pip
        - python {{ python_min }}

  - name: {{ name }}
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(base, exact=True) }}
        - matplotlib-base >=3.5
        - rasterio >=1.3
        - rio-vrt >=0.3
        - scikit-learn >=0.23
        - scipy >=1.5

    test:
      commands:
        - python -m pip check
      imports:
        - osmnx
        - matplotlib
        - rasterio
        - rio_vrt
        - scipy
        - sklearn
      requires:
        - pip
        - python {{ python_min }}

about:
  home: https://osmnx.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: OSMnx is a Python package to easily download, model, analyze, and visualize street networks and other geospatial features from OpenStreetMap.
  description: OSMnx is a Python package to easily download, model, analyze, and visualize street networks and other geospatial features from OpenStreetMap. You can download and model walking, driving, or biking networks with a single line of code then analyze and visualize them. You can just as easily work with urban amenities/points of interest, building footprints, transit stops, elevation data, street orientations, speed/travel time, and routing.
  doc_url: https://osmnx.readthedocs.io
  dev_url: https://github.com/gboeing/osmnx

extra:
  recipe-maintainers:
    - gboeing
    - ocefpaf
